In [1]:
import numpy as np

## Numpy Arrays

In [3]:
#List
list1 = [1, 2, 3, 4, 5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [5]:
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [6]:
# To create a 1 dimenstional array 
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [13]:
a.shape

(4,)

In [12]:
b = np.array([(1, 2, 3, 4), (5, 6, 7, 8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
b.shape

(2, 4)

In [17]:
c = np.array([(1, 2, 3, 4), (5, 6, 7, 8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


##Initial Placeholders in Numpy Arrays

In [18]:
 #To createt a numpy array of zeros
x = np.zeros((4, 5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# To create a numpy array of one
x = np.ones((3, 3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
#To create an array of a particular value
z = np.full((5, 4), 5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [23]:
# To create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
# To create a numpy array with random values
b = np.random.random((3, 4))
print(b)

[[0.31055318 0.91105025 0.21646404 0.33370227]
 [0.40675606 0.05736143 0.4708302  0.61377835]
 [0.1081173  0.55116375 0.01887855 0.00413797]]


In [25]:
# To create an array with random integers
c = np.random.randint(10, 100, (3, 5))
print(c)

[[79 23 33 95 66]
 [61 11 89 45 48]
 [70 87 59 80 20]]


In [30]:
# To create an evenly spaced values - we are specifying the number of values required
d = np.linspace(10, 30, 6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [29]:
# Array of evenly spaced values - specifying the step
e = np.arange(10, 30, 5)
print(e)

[10 15 20 25]


In [33]:
# To convert a list tp a numpy array 
list2 = [10, 20, 20, 20, 50]
np_array = np.asarray(list)
print(np_array)
type(np_array)

<class 'list'>


numpy.ndarray

## Analysing a Numppy Array

In [35]:
c = np.random.randint(10, 100, (5, 5))
print(c)

[[90 12 22 54 22]
 [60 38 56 26 57]
 [88 73 32 13 51]
 [87 93 57 43 63]
 [10 79 63 58 74]]


In [36]:
# To convert to dimension
print(c.shape)

(5, 5)


In [37]:
# To check the number of dimensions
print(c.ndim)

2


In [38]:
# To check the number of elements in an array
print(c.size)

25


In [40]:
# To check the data types of the values in the array
print(c.dtype)

int32


Mathematical Operations on a np array

In [41]:
list1 =  [1, 2, 3, 4, 5]
list2 = [6, 7, 8, 9, 10]

print(list1 + list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [43]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(10, 20, (3, 3))

print(a)
print(b)

[[3 5 9]
 [4 0 2]
 [2 5 1]]
[[19 19 10]
 [15 18 10]
 [16 12 18]]


In [44]:
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))


[[22 24 19]
 [19 18 12]
 [18 17 19]]
[[-16 -14  -1]
 [-11 -18  -8]
 [-14  -7 -17]]
[[57 95 90]
 [60  0 20]
 [32 60 18]]
[[0.15789474 0.26315789 0.9       ]
 [0.26666667 0.         0.2       ]
 [0.125      0.41666667 0.05555556]]


## Array Manipulation

In [48]:
array = np.random.randint(0, 10,(2, 3))
print(array)
print(array.shape)

[[5 9 1]
 [7 8 6]]
(2, 3)


In [49]:
# Transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 7]
 [9 8]
 [1 6]]
(3, 2)


In [50]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[5 7]
 [9 8]
 [1 6]]
(3, 2)


In [51]:
# To reshape an array
a = np.random.randint(0, 10, (2, 3))
print(a)
print(a.shape)

[[7 2 8]
 [0 9 2]]
(2, 3)


In [52]:
b = a.reshape(3, 2)
print(b)

[[7 2]
 [8 0]
 [9 2]]
